#!/bin/bash
if [[ -e $1 ]] ; then
  path=$1
else
  walker_nav="dir,follow,hidden"
  skip="Library,Applications,.local,.cache,.git,miniconda3,node_modules,.config"
  root=$HOME

  path=$(fzf --walker="$walker_nav" --walker-skip="$skip" --walker-root="$root" --tmux)
fi
name="$(basename "$path")"


if [[ -n "$name" ]] ; then
  tmux has-session -t "$name" 2>/dev/null

  # If session doesnt exit
  if [[ $? -ne 0 ]] ; then
    tmux new-session -s "$name" -d -c "$path"
  fi

  # If in tmux
  if [[ -n "$TMUX" ]] ; then
    tmux switch-client -t "$name"
  else
    tmux attach-session -t "$name"
  fi
fi

