#!/usr/bin/env bash
# generate-crt.sh — Generates a per-tmux-pane CRT shader for Ghostty.
# Called by tmux hooks on split/resize/close/layout-change.
# Writes to ~/.config/ghostty/shaders/crt.glsl (runtime-generated, not in dotfiles).

set -euo pipefail

OUTPUT="$HOME/.config/ghostty/shaders/crt.glsl"
mkdir -p "$(dirname "$OUTPUT")"

# ---------------------------------------------------------------------------
# Gather pane geometry
# ---------------------------------------------------------------------------
build_pane_array() {
    if [ -z "${TMUX:-}" ]; then
        # Not inside tmux — single fullscreen pane
        echo "const vec4 panes[1] = vec4[1]( vec4(0.0, 0.0, 1.0, 1.0) );"
        echo "const int paneCount = 1;"
        return
    fi

    # Terminal dimensions in cells
    read -r cols rows <<< "$(tmux display-message -p '#{client_width} #{client_height}')"
    if [ -z "$cols" ] || [ -z "$rows" ] || [ "$cols" -eq 0 ] || [ "$rows" -eq 0 ]; then
        echo "const vec4 panes[1] = vec4[1]( vec4(0.0, 0.0, 1.0, 1.0) );"
        echo "const int paneCount = 1;"
        return
    fi

    # Collect pane rectangles: x, y, width, height (in cells)
    local pane_data
    pane_data="$(tmux list-panes -F '#{pane_left} #{pane_top} #{pane_width} #{pane_height}')"

    local -a entries=()
    while IFS=' ' read -r px py pw ph; do
        # Normalize to 0..1 UV coordinates
        local x y w h
        x=$(awk "BEGIN { printf \"%.6f\", $px / $cols }")
        y=$(awk "BEGIN { printf \"%.6f\", $py / $rows }")
        w=$(awk "BEGIN { printf \"%.6f\", ($px + $pw) / $cols }")
        h=$(awk "BEGIN { printf \"%.6f\", ($py + $ph) / $rows }")
        entries+=("vec4(${x}, ${y}, ${w}, ${h})")
    done <<< "$pane_data"

    local count=${#entries[@]}
    local joined
    joined=$(IFS=','; echo "${entries[*]}")
    # Add spaces after commas for readability
    joined="${joined//,/, }"

    echo "const vec4 panes[${count}] = vec4[${count}]( ${joined} );"
    echo "const int paneCount = ${count};"
}

# ---------------------------------------------------------------------------
# Write the shader
# ---------------------------------------------------------------------------
PANE_UNIFORMS="$(build_pane_array)"

cat > "$OUTPUT" << 'SHADER_HEAD'
// CRT Post-Processing Shader for Ghostty — per-pane barrel distortion
// AUTO-GENERATED by generate-crt.sh — do not edit by hand

// --- Tuning knobs ---
#define CURVATURE       0.03   // Barrel distortion strength
#define ZOOM            0.99   // Slight zoom-in to compensate for barrel shrink
#define CHROM_ABERR     0.0008 // Chromatic aberration RGB split width
#define SCANLINE_WEIGHT 0.25   // Scanline darkening intensity
#define FLICKER_AMP     0.03   // Phosphor flicker amplitude
#define FLICKER_FREQ    60.0   // Phosphor flicker frequency (Hz)

// --- Pane layout (baked at generation time) ---
// Each vec4 = (x_min, y_min, x_max, y_max) in UV space
SHADER_HEAD

echo "$PANE_UNIFORMS" >> "$OUTPUT"

cat >> "$OUTPUT" << 'SHADER_TAIL'

// Find which pane this UV coordinate belongs to.
// Returns pane index, or -1 if none matched.
int find_pane(vec2 uv) {
    for (int i = 0; i < paneCount; i++) {
        vec4 p = panes[i];
        if (uv.x >= p.x && uv.x <= p.z && uv.y >= p.y && uv.y <= p.w) {
            return i;
        }
    }
    return -1;
}

// Barrel distortion relative to a pane's center
vec2 distort_in_pane(vec2 uv, vec4 pane) {
    // Map UV to pane-local 0..1
    vec2 paneSize = pane.zw - pane.xy;
    vec2 local = (uv - pane.xy) / paneSize;

    // Zoom to compensate barrel shrink
    local = (local - 0.5) * ZOOM + 0.5;

    // Barrel distortion in pane-local space
    vec2 cc = local - 0.5;
    float dist = dot(cc, cc);
    local = local + cc * dist * CURVATURE;

    // Map back to global UV
    return pane.xy + local * paneSize;
}

void mainImage(out vec4 fragColor, in vec2 fragCoord) {
    vec2 uv = fragCoord.xy / iResolution.xy;

    int paneIdx = find_pane(uv);

    vec2 duv;
    if (paneIdx >= 0) {
        duv = distort_in_pane(uv, panes[paneIdx]);
    } else {
        // Outside any pane (e.g. pane borders) — no distortion
        duv = uv;
    }

    duv = clamp(duv, 0.0, 1.0);

    // Chromatic aberration (RGB channel split)
    float r = texture(iChannel0, clamp(duv + vec2(CHROM_ABERR, 0.0), 0.0, 1.0)).r;
    float g = texture(iChannel0, duv).g;
    float b = texture(iChannel0, clamp(duv - vec2(CHROM_ABERR, 0.0), 0.0, 1.0)).b;
    vec3 col = vec3(r, g, b);

    // Horizontal scanlines
    float scan = sin(duv.y * iResolution.y * 0.5 * 3.14159) * 0.5 + 0.5;
    col *= (1.0 - SCANLINE_WEIGHT) + SCANLINE_WEIGHT * scan;

    // Phosphor flicker
    col *= 1.0 - FLICKER_AMP * 0.5 * (1.0 + sin(iTime * FLICKER_FREQ));

    fragColor = vec4(col, 1.0);
}
SHADER_TAIL
