#!/usr/bin/env sh

sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

# Auto select recent window on window destroyed
yabai -m signal --add event=window_destroyed action="yabai -m query --windows --window &> /dev/null || yabai -m window --focus recent || yabai -m window --focus first"
yabai -m signal --add event=application_terminated action="yabai -m query --windows --window &> /dev/null || yabai -m window --focus recent || yabai -m window --focus first"

yabai -m config external_bar               all:40:0       \
                mouse_follows_focus        off            \
                focus_follows_mouse        off            \
                window_zoom_persist        off            \
                window_placement           second_child   \
                window_shadow              off            \
                window_opacity             on             \
                window_opacity_duration    0.2            \
                active_window_opacity      1.0            \
                normal_window_opacity      0.8            \
                window_animation_duration  0.5            \
                window_animation_easing    ease_out_quint \
                insert_feedback_color      0xff9dd274     \
                split_ratio                0.50           \
                auto_balance               off            \
                auto_padding               on             \
                mouse_modifier             fn             \
                mouse_action1              move           \
                mouse_action2              resize         \
                mouse_drop_action          swap           \
                                                          \
                top_padding                0              \
                bottom_padding             38              \
                left_padding               8              \
                right_padding              8              \
                window_gap                 10


yabai -m config layout bsp

# Define spaces
MAX_SPACES=4
for idx in $(seq 1 $MAX_SPACES); do
  yabai -m space --create
done

# Remove extra spaces
while yabai -m query --spaces | jq -e ".[] | select(.index > $MAX_SPACES)" > /dev/null; do
  yabai -m space $((MAX_SPACES + 1)) --destroy
done

yabai -m rule --add app="^Zen$" manage=on

skhd --start-service -c ~/.config/skhd/skhdrc &
borders active_color=0xffe1e3e4 inactive_color=0xff494d64 width=5.0 &
keymap load ~/.config/keymap/keymaprc

echo "yabai configuration loaded.."
